### ISSUE TITLE
Undefined error instead of 401 Unauthorized

### ISSUE THREAD

**Issue by RoiEXLab** [NodeBB/nodebb-plugin-write-api#102]
Just noticed this today, it seems like there's a bug in the API that results in an undefined error whenever a route is called without any user authentication information.
Example:
GET https://forums.triplea-game.org/api/v2/users/10/tokens
Returns
```
{"path":"&#x2F;api&#x2F;v2&#x2F;users&#x2F;10&#x2F;tokens","error":"Cannot read property 'uid' of undefined"}
```
My theory is that this error occurs here:
https://github.com/NodeBB/nodebb-plugin-write-api/blob/4eadba6429ccdbd57bc8a0be7bf72833671efe26/routes/v2/users.js#L142

Because there's no user req.user is undefined and therefore an id can't be retrieved.
On the other hand I'd expect the middleware to return 401 before that, but a 500 status code is really not a good sign.
The forum is still using NodeBB v1.10.1 but I don't think that should make a difference because I know a second forum where this happens as well where I'm pretty sure it uses v1.10.2
Also one thing I noticed:
This isn't the case when there's a browser session still active, this means if you log into the forum, don't log yourself out, the correct error code and message will be displayed.

EDIT: When working on #103 I realized the issue: The middleware simply does nothing when no standard authentification mechanisms are available, thus the undefined error.

**Comment by julianlam** [comment]
Please give v5.2.2 a try and see if that resolves for you.

**Comment by julianlam** [comment]
okay, I can't seem to publish write-api at the moment, but I will try again later. If you are around now, just check out latest master and see if that fixes?

**Comment by julianlam** [comment]
https://github.com/NodeBB/nodebb-plugin-write-api/commit/60ca04d3612b86a25ca9bce5c42d65bcbd8331e3

**Comment by RoiEXLab** [comment]
@julianlam I will check, once the new version is listed in the ACP 👍 
Directly checking out master is currently not really an option for me, I'm a little bit in a rush right now, perhaps in a couple of hours or tomorrow morning (In ~12 hours for me)

In any case by simply looking at the change you proposed I'm concerned that this will only fix the status code for this exact route and it will still occur for other routes as well if they don't explicitly check if authentication has been successful.
But maybe I'm missing something and it works nevertheless. I'll check ASAP

**Comment by julianlam** [comment]
That is a good point, I think we'd need to reject the call in this middleware with an error in the `else`...

**Comment by RoiEXLab** [comment]
Just to have mentioned it before I forget it again:
As described in a side note in this issue the session cookie has an effect on the write-api which should probably not be the case IMO.
It could be the case that by fixing the authentication thingy this will get fixed as well because then the core router won't ever get a chance to handle the request, but I don't know the code enough to make a reliable guess.

**Comment by julianlam** [comment]
If it does have an effect, well, why not? It technically _is_ a logged in user, isn't it :smile:

**Comment by RoiEXLab** [comment]
Thinking a little bit more about this, this seems to me like a regression introduced in #100 
I'll be able to check this change in a couple of hours, but I realised I don't know how to link a repository to nodebb anymore.
Wasn't there something like npm link or something like that? 
And will it just work even if the old plugin version still exists?

**Comment by julianlam** [comment]
``` bash
$ cd your_plugin_directory
$ npm link   # or yarn link
$ cd your_nodebb_directory
$ npm link nodebb-plugin-write-api   # or yarn link nodebb-plugin-write-api
```

If there's an installed version, it will remove it.

**Comment by julianlam** [comment]
Okay, so statelessness would mean:

> each request must contain all of the information necessary to be understood by the server, rather than be dependent on the server remembering prior requests.

To that end, the client sending the cookie jar to the server doesn't necessarily violate statelessness, unless I am misunderstanding horribly...

**Comment by RoiEXLab** [comment]
Ok, thanks. 
Just one more question:
How would I roll back this change to be able to control this again from the ACP?

**Comment by julianlam** [comment]
Control installation of write-api? `npm unl nodebb-plugin-write-api` should do the trick (you would then have to re-install via ACP)

**Comment by RoiEXLab** [comment]
@julianlam Well in this case the server stores the information about the cookie which is some sort of state?
I really don't care about this, just thought it's unexpected to get a different error message due to this behaviour.

**Comment by julianlam** [comment]
Ah yeah #100 is different because it changes the meaning of the method `requireUser`... in fact, that it is no longer **requiring** a user :thinking: 

I'll have to give it some thought.

**Comment by RoiEXLab** [comment]
@julianlam Ok, after messing around with npm and upgrading nodebb from a super old version I still had lying around locally I finally was able to test this.
The error message for this specific route is indeed fixed 👍 
However as I expected the same `Cannot read property 'uid' of undefined` error occurs for other routes.

**Comment by RoiEXLab** [comment]
Does the deployment issue still persist?
It'd need the latest master for a productive environment (because of the subfolder issue, not this one)

**Comment by julianlam** [comment]
v5.2.2 is published now
