### ISSUE TITLE
"Follow" route

### ISSUE THREAD

**Issue by d0dge** [NodeBB/nodebb-plugin-write-api#105]
I'm slightly confused by the follow route, i.e. "POST /:uid/follow".

It states that the purpose is to follow another user, but accepts no parameters.  Shouldn't it take the "other user" parameter?  So ":uid" is the following user and the parameter is the followed user.

**Comment by julianlam** [comment]
When you use the bearer token, that is the user that is doing the following. If using a master token, then you are passing in `_uid` via query param, so again the following uid is defined.

Therefore `:uid` is the user that is followed. Hopefully that makes it clearer :smile:
