### ISSUE TITLE
what is current?

### ISSUE THREAD

**Issue by XLYJXLYJ** [NodeBB/nodebb-plugin-write-api#107]
hi,i want to change the password,but i dont  how to use PUT /:uid/password,and what is current,i need your help ,thnaks

**Comment by julianlam** [comment]
What have you tried? Post a cURL command for me to correct.

**Comment by XLYJXLYJ** [comment]
https://www.manykit.com/forum/:uid/passwrd?uid=XXX&new=XXX, is it right?

**Comment by XLYJXLYJ** [comment]
https://www.manykit.com/forum/:uid/passwrd?uid=XXX&new=XXX, is it right? @julianlam

**Comment by julianlam** [comment]
`current` is the current password. If you are not using a master token, then you need to send it in.

`curl -X PUT https://www.manykit.com/forum/:uid/password --data "_uid=adminUid&new=newPassword`

`uid` is actually not required, I will remove that from readme.

**Comment by julianlam** [comment]
53e8dcb

**Comment by XLYJXLYJ** [comment]
thank you for answer my question，thank you very much， best wish


发自网易邮箱大师
On 12/8/2018 00:10，Julian Lam<notifications@github.com> wrote：

current is the current password. If you are not using a master token, then you need to send it in.

curl -X PUT https://www.manykit.com/forum/:uid/password --data "_uid=adminUid&new=newPassword

uid is actually not required, I will remove that from readme.
