### ISSUE TITLE
Missing GET methods

### ISSUE THREAD

**Issue by ilblog** [NodeBB/nodebb-plugin-write-api#108]
While default read NodeBB /api returns content already in html there would be nice to get it in raw MD format.

**Comment by julianlam** [comment]
I would prefer to keep GET methods in core actually... however, in this case because markdown isn't used in all composers, putting it in core does not make sense (nor does it work in write-api). If you want raw markdown via API perhaps markdown plugin can expose the appropriate route?

**Comment by julianlam** [comment]
v8.9.0 of nodebb-plugin-markdown
