### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by thehelloand** [NodeBB/nodebb-plugin-write-api#111]
Installed the plugin and now receiving this error in console: 
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'router' of undefined

**Comment by julianlam** [comment]
Install one version older for now. Or potentially upgrade Node if you're not on V8+

**Comment by alfazaz** [comment]
Same problem for me (on nodebb 1.12.2 and with your 5.5.1 plugin version). 

It's on startup. Here is the relevant part of my logs when I do a nodebb dev :

> 2019-08-27T15:26:26.627Z [5678/5142] - verbose: [plugins/fireHook] action:plugins.firehook
> (node:5142) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'router' of undefined
>     at module.exports (/home/hidden/hidden/Developpement/nodebb/node_modules/nodebb-plugin-write-api/routes/v2/index.js:52:23)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
> (node:5142) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
> (node:5142) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> 2019-08-27T15:26:26.711Z [5678/5142] - verbose: [plugins/fireHook] action:markdown.updateParserRules
> 2019-08-27T15:26:26.713Z [5678/5142] - verbose: [plugins/fireHook] action:plugins.firehook
> 2019-08-27T15:26:31.550Z [5678/5142] - warn: [plugins] Callback timed out, hook 'static:app.load' in plugin 'nodebb-plugin-write-api'
> 2019-08-27T15:26:31.550Z [5678/5142] - verbose: [plugins/fireHook] action:plugins.firehook
> 2019-08-27T15:26:31.551Z [5678/5142] - verbose: [plugins] All plugins reloaded and rerouted

**Comment by alfazaz** [comment]
Ok. So we need to downgrade this plugin or upgrade nodebb to 1.13 when it will be out (soon ?). It's that ?

**Comment by alfazaz** [comment]
OK. Thanks.
