### ISSUE TITLE
500 Internal Server error on PUT users with email already taken

### ISSUE THREAD

**Issue by Brutus5000** [NodeBB/nodebb-plugin-write-api#114]
**Steps to reproduce:**

Create 2 user accounts.
Use the endpoint PUT /api/v2/users/ to set the email of user A to the email of user B.

**Expected result:**
Http statuscode of 400 or comparable

**Actual result:**
Http statuscode 500
Additionally the log says:
> Missing translation "error:email-taken"

It's not a big deal, as the error code itself is clearly stating the problem. I just noticed it on coincidence.

**Comment by julianlam** [comment]
Thanks, will take a look :smile:

**Comment by julianlam** [comment]
v5.5.4
