### ISSUE TITLE
2FA

### ISSUE THREAD

**Issue by RoiEXLab** [NodeBB/nodebb-plugin-write-api#121]
Hi, I'm currently using the write API in order to perform semi-automated posts from a client side application.
Recently the question came up if 2FA works for the write-api as well and it doesn't.

Would it be possible to change the `POST /api/v2/users/:uid/tokens` endpoint in a way so 2FA is actually "honoured", so there isn't a way to bypass the 2FA?

Something simple like appending the one-time-code to the password seems like a reasonable thing to do IMO

**Comment by julianlam** [comment]
@RoiEXLab oof, this is a neat idea!

It's a little harder only because Write API is actually being deprecated in NodeBB v2 and is going into core :grimacing:, but besides that I don't actually see too many blockers... let me see if I can make this happen.

That said, wouldn't you want 2FA enabled on every endpoint, not just `/tokens`?

**Comment by julianlam** [comment]
Oh, I see what you mean, `POST /api/v2/users/:uid/tokens` is like the login endpoint that needs securing via 2FA, otherwise you could bypass 2FA by using write API, got it :ok_hand:

**Comment by RoiEXLab** [comment]
@julianlam Exactly

**Comment by julianlam** [comment]
* Write API v5.7.0
* 2factor v2.7.0

**Comment by julianlam** [comment]
2factor will look for `x-two-factor-authentication` header on the token generation POST route

**Comment by RoiEXLab** [comment]
@julianlam So I would send something like
```
x-two-factor-authentication: 123456
```
where 123456 is the OTP token right?

**Comment by julianlam** [comment]
You got it :+1: Let me know if it doesn't work.

**Comment by RoiEXLab** [comment]
It will take me a while to update the forum to the latest version and implement that api change, but I will ^^

**Comment by 0312birdzhang** [comment]
I used `POST /api/v2/users/:uid/tokens` with `password` body and `x-two-factor-authentication` header, get token successfully, but when i use this token next time, url will be redirect to `/login/2fa?next=/topic/2` etc.. Seems i need reset `x-two-factor-authentication`, can i use token only with api?

**Comment by julianlam** [comment]
@0312birdzhang The x-two-factor-authentication challenge should only be required when you call `POST api/v3/users/:uid/tokens`, what route are you calling?

**Comment by julianlam** [comment]
Actually, if you're seeing `next` as `/topic/2`, then you're not calling the token against the Write API, but a core route, which will trigger a 2FA check. This is intentional behaviour.
