### ISSUE TITLE
Timeout since upgrade with API v2

### ISSUE THREAD

**Issue by aworobel** [NodeBB/nodebb-plugin-write-api#122]
Hello,

I have a problem since i updated writeapi to the latest version (5.7.2)
Indeed it timeouts and no specials logs in Nginx.
My NodeBB version is the latest : v1.13.2

Thanks for your help :)

Arnaud

____________________________________
**** Command :** 
curl -X GET -v -H "Authorization: Bearer bxxxxxxxxxx" --data "_uid=1" http://localhost/api/v2/users/1/tokens

**** Result :** 

Trying 127.0.0.1...
TCP_NODELAY set
Connected to localhost (127.0.0.1) port 80 (#0)
GET /api/v2/users/1/tokens HTTP/1.1
Host: localhost
User-Agent: curl/7.58.0
Accept: */*
Authorization: Bearer bxxxxxxxxxx
 Content-Length: 6
Content-Type: application/x-www-form-urlencoded

upload completely sent off: 6 out of 6 bytes
 HTTP/1.1 504 Gateway Time-out
 Server: nginx/1.17.10
 Date: Thu, 23 Apr 2020 09:46:20 GMT
 Content-Type: text/html
 Content-Length: 168
 Connection: keep-alive

<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.17.10</center>
</body>
</html>
Connection #0 to host localhost left intact

**Comment by aworobel** [comment]
Hi @julianlam and thanks for your message.
Yes it seems to be general on v2 (get / put)
v1 commands are ok.

**Comment by barisusakli** [comment]
Does it work if you downgrade this plugin to 5.6.0?

**Comment by aworobel** [comment]
Hello @barisusakli , just downgraded to 5.6.0 this morning, worked like a charm.

**Comment by julianlam** [comment]
Thanks guys, will take a look and see what the underlying issue is :smile: looks like a regression

**Comment by julianlam** [comment]
8d222712e12cd484018d328f97a0d6190201b7cd
