### ISSUE TITLE
This plugin doesn't appear in the list of the write plugins in my admin screen

### ISSUE THREAD

**Issue by mooreds** [NodeBB/nodebb-plugin-write-api#123]
Only forks are shown. Unclear how to get this plugin in the admin interface.
![image](https://user-images.githubusercontent.com/91825/81457031-e646ce80-9151-11ea-81ef-f1f12f0d4688.png)

**Comment by julianlam** [comment]
Hi @mooreds -- the top entry is this plugin :smile:

**Comment by mooreds** [comment]
Ah, my bad. I thought that it'd need to be under the https://github.com/NodeBB/ org. Sorry!

**Comment by julianlam** [comment]
No worries 😁 do let me know how you get on with the plugin.
