### ISSUE TITLE
Warn or prohibit creation of new user of same username

### ISSUE THREAD

**Issue by alfazaz** [NodeBB/nodebb-plugin-write-api#129]
Hello !

When we create a new user with a username which already exists, it is created with an appended number as stated in documentation, but there is no warn about this... So, if we don't want to create the user if username already exists, we need to check it before using read API and it's not practical (and also, I have a fail for now with it because of https://github.com/NodeBB/NodeBB/issues/8487 ...).

Won't it be greater to (at your choice) :
* Prohibit creation of user with already existing username (like for email)
* Or return a message indicating the username change...
?

Thanks in advance for your answer.

**Comment by julianlam** [comment]
Sorry for the delay -- in new v3 of write-api (which will be merged in core), I have the following non-breaking change noted already:

> The POST route will now return a complete user object (a call to User.getUserData is made with the new uid)

So the new username will be specified there.

**Comment by alfazaz** [comment]
Ok, thanks !
