### ISSUE TITLE
[Question] Create Topic as Current User

### ISSUE THREAD

**Issue by 654wak654** [NodeBB/nodebb-plugin-write-api#131]
Hello, I'm confused about how to use the write API for a really simple task.

I have a form page in my nodebb. When a user "submits" the form, I want to make a request to the write api and create a topic as that user. I don't want to generate a token from the admin panel as that seems like it would grant too much power to this client side script. I want to do something the user can already do, but just automate it. How could I go about doing this?

This is what I'm doing atm, but obviously I get a 400:
```js
// This runs on button click
fetch("/api/v2/topics", {
    method: "POST",
    headers: {
        // Token goes here?
    },
    body: JSON.stringify({
        cid: 12,
        title: "Testo mesto",
        content: "watwat"
    })
}).then(res => console.log(res));
```

**Edit:** Kind of irrelevant question: Does the POST topic endpoint return anything? I'd like to redirect the user to the topic after it's created.

**Comment by julianlam** [comment]
This is how the write-api works, you'd have to generate a token as that's one of the ways you can programmatically make a call to a NodeBB.

If you don't want to pass a token, but the user is logged into NodeBB, you can pass in the cookie (that's fetch `withCredentials: true` I think), and that ought to work too, but I cannot guarantee that :smile:

**Comment by 654wak654** [comment]
Thanks I'll try the cookie way. Think I understand the purpose of the plugin better now.

Might figure out how nodebb itself creates a topic too.
