### ISSUE TITLE
Access to admin pages with master token

### ISSUE THREAD

**Issue by cryptoethic** [NodeBB/nodebb-plugin-write-api#132]
Hi!

This plugin allow us by using master token to make a call in name of another user by specifying _uid param. It works great for non admin api calls..

But there is a problem when calling admin api url, which might be hard to describe for me but I will try ;-)

Assume that all following requests are made with master token and _uid=1 is super admin. Inside session I keep cookies sent by server.

Session 1:
http://localhost:4567/api/unread?_uid=1 (this request sets proper cookies)
http://localhost:4567/api/admin?_uid=1 

In second request we will receive correct response

Session 2:

http://localhost:4567/api/admin?_uid=1

We will receive 401 "not-authorized" error.

----

I found out that problem lays in nodebb `src/routes/index.js` module.exports function where express router is defined.
There is a regex here:
```
	router.all('(/+api/admin|/+api/admin/*?)', middleware.admin.checkPrivileges);
```
which executes before `filter:router.page` hook and checkPrivileges middleware rejects request.

Changing this line to 
```
	router.all('(/+api/admin|/+api/admin/*?)', middleware.pluginHooks, middleware.admin.checkPrivileges);
```

resolves my problem, but it might not be the best way of doing it. 

Can I ask for any help with that? 
Maybe there is another advised way of accessing admin routes from third party services, which will not require logging and maintaining session?

**Comment by cryptoethic** [comment]
To be honest I cannot be sure if adding pluginHooks middleware is safe for all `api/admin` routes.
I resolved my problem by defining route that does not contain `admin` keyword in my plugin and restricting access to only admins by:

```
	router.get('/api/plugins/third-party-integration/subscriptions/:uid', hostMiddleware.pluginHooks, hostMiddleware.admin.checkPrivileges, NodeBB.helpers.tryRoute(controllers.getUserSubsriptions));

```

This route can be called only by admins or with master token and admin _uid.

It does not resolve the above problem (that requests order affect response access)

**Comment by julianlam** [comment]
Can you perhaps try with the new write API bundled in core with v1.15.x? You may be able to use your token to access admin pages now.

**Comment by julianlam** [comment]
Ah, nope, no, this still does not work, heh

**Comment by julianlam** [comment]
Right now it grants you access to the `/api` routes. HTML access to those pages is unchanged (not quite sure why you'd want the HTML, too)

**Comment by cryptoethic** [comment]
Hey @julianlam !

Thanks for answer! `/api/admin/*` routes are good enough I believe.

Thank you for merging write api with nodebb core - great feature!
