### ISSUE TITLE
Revoke Session via Write API

### ISSUE THREAD

**Issue by uplift** [NodeBB/nodebb-plugin-write-api#133]
Should it be possible to revoke a session via the Write API?

https://github.com/NodeBB/NodeBB/blob/391102766fb4e0eb04e86a6bb1bcf711352ff3bc/src/routes/accounts.js#L42

In my attempts it gets caught in middleware.ensureSelfOrGlobalPrivilege as not being req.loggedIn. Do the delete requests go through this plugins requireUser middleware to login?
 
https://github.com/NodeBB/NodeBB/blob/391102766fb4e0eb04e86a6bb1bcf711352ff3bc/src/middleware/user.js#L64

**Comment by julianlam** [comment]
Makes sense to allow this via write API. The existing route in NodeBB core should be migrated to the `api/v3` style, and then it should work with the bearer token.
