### ISSUE TITLE
Upload functionality has been broken

### ISSUE THREAD

**Issue by RoiEXLab** [NodeBB/nodebb-plugin-write-api#134]
With the changes in https://github.com/NodeBB/NodeBB/blob/master/src/upgrades/1.13.4/remove_allowFileUploads_priv.js the upload endpoint becomes broken because of this line:
https://github.com/NodeBB/nodebb-plugin-write-api/blob/92b227613672190690be26438ed24dfa45b98d65/routes/v2/util.js#L16

I suppose the easiest fix would be to just remove the if statement?

**Comment by julianlam** [comment]
Ah we can just update the conditional to check for privilege too

**Comment by julianlam** [comment]
df8fca5233ab1487d2c18c48d998e4bb96428932

**Comment by RoiEXLab** [comment]
@julianlam After updating the plugin to 5.8.2 I'm still getting the same error on v1.14.3 using a user token

**Comment by julianlam** [comment]
:(

**Comment by julianlam** [comment]
I am also using a user token, and I am not running into issues... are you sure the user associated with that token has the `upload:post:file` privilege?

![image](https://user-images.githubusercontent.com/923011/98882137-a098f480-2459-11eb-8a88-551d56808750.png)

**Comment by Keine-Andeutung** [comment]
The problem is with the same account I can upload files manually but not automatically the program loading up files.

**Comment by RoiEXLab** [comment]
See https://github.com/julianlam/nodebb-plugin-2factor/pull/52
