### ISSUE TITLE
How to delete user account + content? 

### ISSUE THREAD

**Issue by onasman** [NodeBB/nodebb-plugin-write-api#139]
Does the `DELETE /:uid` endpoint also delete the user content? 
If not, how do I delete both the user and the user content with this plugin?
Would be good if it can be done within this plugin without updating the project in order to use the new built-in write api.

**Comment by julianlam** [comment]
Hello @onasman -- thanks for the question. The Write API's `DELETE /v2/users/:uid` endpoint was created before we differentiated between deleting an account, vs deleting its content.

So if you call this route, it will **delete both the account and its content**.

**Comment by onasman** [comment]
Thanks for a quick reply! 👍

**Comment by onasman** [comment]
@julianlam do you know why I'm not able to create a master token? Running NodeBB v1.12.2
https://user-images.githubusercontent.com/59735181/105373377-ea931900-5c06-11eb-8c34-f60eb88ba901.mov
