### ISSUE TITLE
Update Topic call not working 

### ISSUE THREAD

**Issue by surajdalvi** [NodeBB/nodebb-plugin-write-api#18]
I want to add tags to post so i use **PUT** call like **/api/v1/topics/tid**  and send tag array in body but it give response  like invalid api call 

please help me

**Comment by julianlam** [comment]
Can you show me this not working as a `curl` statement?

**Comment by snippetsam** [comment]
I'm also having an issue with this; I'm getting "Invalid API call" response. 

I may be mistaken, but I've just had a look at the code and it seems that the 'put' for '/topics/:tid' route isn't in place? 

There is a route for 'put' in 'topics/' though, which I can't see in the documentation.

Is this an issue with how we're calling the api, or is there an issue? 

Thanks.

**Comment by julianlam** [comment]
I'll have to take a look. If it is `PUT /topics`, that's not really right. It should be `PUT /topics/:tid`

**Comment by julianlam** [comment]
You guys will want to use `POST/DELETE /topics/:tid/tags` now

**Comment by surajdalvi** [comment]
yes
