### ISSUE TITLE
Please explain what does "Any other data passed in will be saved into the user hash" means

### ISSUE THREAD

**Issue by trancephorm** [NodeBB/nodebb-plugin-write-api#189]
/api/v2
    /users
        POST /
            Creates a new user
            Requires: username (In case it's taken, nodebb will append a number.)
            Accepts: password, email
            **Any other data passed in will be saved into the user hash**

I was thinking somehow this may be the way to insert custom field when creating new user, but the property I submit just gets ignored.

Anyways, is there any way to have some custom fields within users?

**Comment by julianlam** [comment]
It could be that this is how `user.create()` used to work, but it no longer blindly accepts any custom data as it may pollute the user hash.

If you do want to pass custom data in to save in the user hash, you'll have to explicitly add it to the logic by adding a hook listener to `filter:user.create`.

That hook passes `user` and `data`, the former being the hash to-be-saved, and the latter being what was received by the server.
