### ISSUE TITLE
Unable to Create API Token

### ISSUE THREAD

**Issue by sotarules** [NodeBB/nodebb-plugin-write-api#22]
I'm using Node.js 0.10.36 with NodeBB v0.6.1.  I'm a brand new user of NodeBB as of yesterday, and I have it installed and running on Ubuntu 14.04 (Amazon EC2).

The system is up, but one of our requirements involves creating users from an external system.  I've installed the NodeBB Write API plugin via the ACP:

![writeapi1](https://cloud.githubusercontent.com/assets/5454239/7435325/a91d0d86-eff7-11e4-8659-8c255e9aa779.png)

I have successfully restarted NodeBB, but I'm unable to create the API token.  When I try to navigate to admin/plugins/write-api in order to generate the token, I'm receiving this message:

`/api/admin/plugins/write-api Not Found`
`not-found`

![writeapi2](https://cloud.githubusercontent.com/assets/5454239/7435361/f91bd3f8-eff7-11e4-9e0f-f9af598b3146.png)

Am I going to the right place to do this, or is there something I'm missing (either in my own understanding or configuration)?

Thanks in advance.

**Comment by julianlam** [comment]
Hello @sotarules, the Write API plugin is only compatible with v0.7.0, which is not yet released. You'll need to update your core code to utilise the `master` branch. Otherwise, you can wait until v0.7.0 is released. :smile:

**Comment by sotarules** [comment]
Julian Lam thanks for the amazingly quick response.  Since our installation is brand new and we don't have a user base to worry about, I'll update our system 0.7.0 and try again.

**Comment by sotarules** [comment]
Julian, I have v0.7.0 working.  Thanks for you help with that, but I've run into another snag.

I'm trying to POST to /users to create a new user record.  Here is the POST request:

`curl -v -H "Authorization: Bearer 7962a4b4-504a-41f0-b669-c7b02c696f27" --data "username=Wiley&password=practus&email=wiley%40pract.us" http://localhost:4567/api/v1/users`

When I do this, I get HTTP 200 response:

`{"code":"ok","payload":{"uid":null}}`

I think the system may have made a junk record, because when I search using the first characters of the name "Wiley" I find a user, but the name is shown as `[[global:guest]] (0)`

Please bear with me as I'm completely new to NodeBB.

**Comment by julianlam** [comment]
Hm, did you run `./nodebb setup` after updating to v0.7.0? The `null` response is indicative of an incompatible `mongodb` module.

Can you also run `npm ls mongodb`?

**Comment by sotarules** [comment]
Julian, I had not run ./nodebb setup after updating, so I did just now.

You are right BTW that I'm using MongoDB.  I ran **npm ls mongodb** and here is the result:
```
bitnami@ip-172-31-18-193:~/nodebb$ npm ls mongodb
nodebb@0.7.0-dev /home/bitnami/nodebb
└── mongodb@2.0.28  extraneous

npm ERR! extraneous: mongodb@2.0.28 /home/bitnami/nodebb/node_modules/mongodb
npm ERR! not ok code 0
bitnami@ip-172-31-18-193:~/nodebb$ 
```

**Comment by sotarules** [comment]
Julian after running ./nodebb setup, it seems to have fixed it.  I just ran the CURL command again and check this out, here is my new user **Wiley**:

![image](https://cloud.githubusercontent.com/assets/5454239/7439432/07c34520-f030-11e4-9545-3ad9e25d9ecb.png)

**Comment by julianlam** [comment]
Awesome! Glad it's working out for you :smile:, and glad I could help.
