### ISSUE TITLE
No bearer authentication for Read API

### ISSUE THREAD

**Issue by avraham1** [NodeBB/nodebb-plugin-write-api#237]
Problem like this: https://github.com/NodeBB/nodebb-plugin-write-api/issues/54

Trying to ask a user by email, in a browser with a session it works, in a server with a token it returns not-authorized.

![1](https://user-images.githubusercontent.com/16626693/190871533-a4040fcb-7036-4461-a594-61a481c0238e.png)

NodeBB 1.17.1 Into docker container

Thanks!

**Comment by julianlam** [comment]
Bearer tokens generated by the v2 write API plugin cannot be used by the v3 read API.

You'll have to generate an API key via ACP > Settings > API Access.

**Comment by avraham1** [comment]
Of course, this token is not created with a plugin, it is a token from the API Access interface.

**Comment by avraham1** [comment]
Why is it closed? Is there anything new about it?

**Comment by avraham1** [comment]
Just want to update, I upgraded the forum to version 2.5.7 and it works well.

Thank you so match!
