### ISSUE TITLE
Group Creation

### ISSUE THREAD

**Issue by snippetsam** [NodeBB/nodebb-plugin-write-api#25]
Awesome plugin guys - just what I need! 

I can see in the api there is a route for creating a new group, but the logic is missing. Obviously, group creation is not in the published list of end points, but is this planned to be implemented any time soon? It seems like a fairly quick implementation? Or am I missing something? 

Thanks.

**Comment by julianlam** [comment]
Please use v3.0.8, which includes this new route :smile:

**Comment by snippetsam** [comment]
Perfect timing! 

Thanks.
