### ISSUE TITLE
forbidden:You are not authorised to make this call

### ISSUE THREAD

**Issue by misterch0c** [NodeBB/nodebb-plugin-write-api#31]
I guess I must be doing something wrong but I can't figure it out..
![img](http://i.imgur.com/aEq0iW2.png)

So I'm using the master token along with _uid. I generated the token with the uid "1" which is an admin user.
I also tried only with the user token but then I get
<pre>
{
  "code": "params-missing",
  "message": "Required parameters were missing from this API call, please see the \"params\" property",
  "params": [
    "username"
  ]
}
</pre>

**Comment by julianlam** [comment]
Hey @misterch0c, user and master tokens are not meant to be used together. A master token is *user-unspecific*, meaning you need to specify a `_uid`, whereas a user token is tied to a user. That's the main difference.

In your case, give this curl call a try:

``` bash
$ curl -X POST http://localhost:4567/api/v1/users --data "username=test&password=testtest&email=test@gmail.com" -H "Authorization: Bearer {TOKEN}"
```

Replace `{TOKEN}` as necessary, and add a `_uid` field in the `--data` portion if using a master token.

**Comment by julianlam** [comment]
`_uid`, by the way, is an integer, and corresponds to the user's internal uid in NodeBB itself.

**Comment by misterch0c** [comment]
Thx for your answer julianlam. I guess that's more a postman issue actually because everything is working smothly with curl. Though I can't seem to do anything from postman with the same parameters and tokens

**Comment by julianlam** [comment]
@misterch0c I actually use postman to test, so perhaps something is off there. If you want me to take a look, please post another picture :smile:
