### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by ItsJamesJ** [NodeBB/nodebb-plugin-write-api#33]
Hi,
Any way that I can connect to the API using Java?
I am doing this:

` con.setRequestProperty("Authorization", "Bearer <my-key>");`	

But I get this: 
`Server returned HTTP response code: 401 for URL:`

Any ideas?

Thanks.

**Comment by julianlam** [comment]
Hey there! 

There should be no issue with using this plugin from a java app. It is just a RESTful API  :smile:

If you're running into issues with Unauthorized errors, please try to reproduce via cURL and paste the nonworking command here.
