### ISSUE TITLE
Is there a way to set permissions (privileges) through endpoints?

### ISSUE THREAD

**Issue by ghost** [NodeBB/nodebb-plugin-write-api#38]
It would be great to have it. Like, creating a group will give you an option to set privileges for it.

**Comment by julianlam** [comment]
Unfortunately at this point in time, no, although it may be added in the future.

**Comment by jkirkpatrick** [comment]
That doesn't sound like it's un-possible, but I'm fairly new to nodebb. Is it low-priority or are there some major blockers?  Should be in it's own sub-plugin instead of write api?

Category permissions is a requirement for me... I would be more than happy to submit a PR.

**Comment by mkranjec** [comment]
@julianlam I would like to help with this issue. Are you willing to provide some hints how to implement this feature?

**Comment by julianlam** [comment]
@mkranjec As privileges are assigned on a per-category basis, you'd want to create new `PUT` and `DELETE` routes in this file: https://github.com/NodeBB/nodebb-plugin-write-api/blob/master/routes/v1/categories.js

Perhaps you could pass in a query-string like so: `?privilege=groups:read&id=registered-users` to allow registered users to read posts in cid 15. Likewise, `DELETE` to remove. Perhaps `?privilege[]=` to add/remove multiple privileges.

You'll need checks to ensure the `id` passed in is a legitimate user or group. Privileges starting with `group:` only allow groups (obviously), so you can determine whether to call `User.exists()` or `Groups.exists();` based on the privilege name.

For API completion, you'd probably want to also expose a `GET` route for each category (e.g. `/api/v1/categories/:cid/privileges`) that would list the privileges for each user/group with a Boolean value denoting whether they have it or not.

**Comment by leroydev** [comment]
Is there still interest in this? For a hobby project, I've implemented this a while back. https://github.com/leroydev/nodebb-plugin-write-api/commit/754974122c42f0df0b013be15e6fc5cbb94bdc1b

**Comment by julianlam** [comment]
Yes, if you open a PR I can merge with some minor changes, like changing the route name to match existing nomenclature, and small stylistic suggestions. Thanks.

**Comment by leroydev** [comment]
@julianlam done :)
