### ISSUE TITLE
Cannot POST /api/v1/users in NodeBB 0.8.2

### ISSUE THREAD

**Issue by astucieuxzephyr** [NodeBB/nodebb-plugin-write-api#41]
When I'm doing the following  with HTTPS (and without certificate using option --insecure) I get a message :
**HTTP/1.1 404 Not Found**
**Cannot POST /api/v1/users**

$ curl -X POST --insecure -v -H "Authorization: Bearer MASTER_TOKEN_HERE" --data "_uid=1&username=Toto&password=MotDePasse&email=toto%40yop
mail.com" https://xxxxxxxxx.nodebb.com/api/v1/users
* Adding handle: conn: 0x4dd2a8
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x4dd2a8) send_pipe: 1, recv_pipe: 0
* About to connect() to xxxxxxxxx.nodebb.com port 443 (#0)
*   Trying XXX.XXX.XXX.XXX...
* Connected to xxxxxxxxx.nodebb.com (XXX.XXX.XXX.XXX) port 443 (#0)
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using DHE-RSA-AES256-SHA
* Server certificate:
*        subject: OU=Domain Control Validated; OU=PositiveSSL; CN=nodebb.org
*        start date: 2013-12-12 00:00:00 GMT
*        expire date: 2017-03-11 23:59:59 GMT
*        issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN
=COMODO RSA Domain Validation Secure Server CA
*        SSL certificate verify result: self signed certificate in certificate c
hain (19), continuing anyway.
> POST /api/v1/users HTTP/1.1
> User-Agent: curl/7.30.0
> Host: xxxxxxxxx.nodebb.com
> Accept: */*
> Authorization: Bearer MASTER_TOKEN_HERE
> Content-Length: 65
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 65 out of 65 bytes
**HTTP/1.1 404 Not Found**
* Server nginx/1.4.6 (Ubuntu) is not blacklisted
< Server: nginx/1.4.6 (Ubuntu)
< Date: Sat, 24 Oct 2015 00:41:52 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 26
< Connection: keep-alive
< X-Powered-By: NodeBB
< Cache-Control: max-age=0
< X-Content-Type-Options: nosniff
< Vary: Accept-Encoding
<
**Cannot POST /api/v1/users**
* Connection #0 to host XXXXXXXXX.nodebb.com left intact

**And I don't know if it's linked, but when I go to watch the logs into NodeBB I see :**

20/10 12:33 [867] - warn: [plugins/load] The following plugins may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing. In the event of an unresponsive NodeBB caused by this plugin, run ./nodebb reset -p PLUGINNAME to disable it.
  * nodebb-plugin-saas-pageviews

20/10 12:33 [867] - info: NodeBB Ready
20/10 12:33 [867] - info: Enabling 'trust proxy'
20/10 12:33 [867] - error:  Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1129:14)
    at listen (net.js:1155:10)
    at Server.listen (net.js:1240:5)
    at listen (/home/saas/nodebb/src/webserver.js:180:17)
    at /home/saas/nodebb/src/webserver.js:57:3
    at EventEmitter.<anonymous> (/home/saas/nodebb/src/emitter.js:17:5)
    at EventEmitter.emit (events.js:104:17)
    at /home/saas/nodebb/src/meta/js.js:203:12
    at FSReqWrap.oncomplete (fs.js:99:15)
20/10 12:33 [867] - error: NodeBB address in use, exiting...
[cluster] Child Process (867) has exited (code: 0, signal: null)

**Comment by julianlam** [comment]
Looks like issue resolved by activating ssl
