### ISSUE TITLE
Error 401 : A valid login session was not found

### ISSUE THREAD

**Issue by astucieuxzephyr** [NodeBB/nodebb-plugin-write-api#42]
When I'm using CURL in PHP I get the following error (401) :
A valid login session was not found. Please log in and try again.

When I'm using a token, is it normal to have to connect in a session to use CURL with the API ?

**Comment by julianlam** [comment]
No, a session is not required. The token acts as a session.

How are you sending in the token? Use header instead of authorisation
curlopt if possible.

**Comment by julianlam** [comment]
Could be mistaken but basic auth is different from bearer auth.

**Comment by astucieuxzephyr** [comment]
Thank your help Julian. I finally found why I was getting this message "A valid login session was not found. Please log in and try again." : In fact there was a mistake in the CURL Header that I was sending with curl_setopt() : I was using the option passing an array() in parameter with array("Authorization:"=>"Bearer MASTER_TOKEN") instead of passing : array("Authorization: Bearer MASTER_TOKEN").
