### ISSUE TITLE
How to format a request with JSON web tokens

### ISSUE THREAD

**Issue by codecowboy** [NodeBB/nodebb-plugin-write-api#43]
The following request is failing for me. It seems I need to use JWT as otherwise I would require setting the authorisation header which I can't do for my particular use case. How should the 'params' property be sent in the following request using JWT?
```
POST http://kommunitynodebb.myurl.com/api/v1/topics/
Content-Type: application/x-www-form-urlencoded
token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfdWlkIjoxfQ.pbm5wbAZ4__yFh5y8oeCsJyT0dm8ROcd5SEBr4yGlNw&cid=1&content=test&title=test2
 -- response --
400 Bad Request
Server:  nginx
Date:  Mon, 02 Nov 2015 14:10:49 GMT
Content-Type:  application/json; charset=utf-8
Content-Length:  160
Connection:  keep-alive
x-powered-by:  NodeBB
x-frame-options:  SAMEORIGIN
Etag:  W/"a0-Bkpgj5XtpAFQx9ys8ARRzQ"
Vary:  Accept-Encoding

{"code":"params-missing","message":"Required parameters were missing from this API call, please see the \"params\" property","params":["cid","title","content"]}

```

**Comment by codecowboy** [comment]
Do the params need to be encoded into the web token? If so that won't for me either. I'd like to connect to the API from the IFTTT Maker channel which doesn't allow manipulation of the Http Headers

**Comment by julianlam** [comment]
Hi @codecowboy -- the payload values need to be embedded in the web token itself. No manipulation of th HTTP headers is required when using JWT.

**Comment by codecowboy** [comment]
@julianlam thanks. I was looking at hitting the API from a webhook which is part of the IFTTT Maker channel. Unfortunately I would need to pass the bearer token as part of the request body as there is no provision for encoding a JWT or setting a header. 

From lib/node_modules/passport-http-bearer/strategy.js it looks like you have disabled this option somehow:
```
  if (req.body && req.body.access_token) {
    if (token) { return this.fail(400); }
    token = req.body.access_token;
  }

  if (req.query && req.query.access_token) {
    if (token) { return this.fail(400); }
    token = req.query.access_token;
  }

  if (!token) { return this.fail(this._challenge()); }

```
Is that the case? tried altering that code but didn't get anywhere.

**Comment by julianlam** [comment]
I didn't modify http-bearer (you'll notice it's not in the repo files). You'll need to encode the payload in the actual `POST` payload or `GET` querystring parameter.

**Comment by codecowboy** [comment]
Hmmm, I am confused then. I see now that you are pulling in passport-http-bearer as a dependency - apologies.

I guess this comment in that file is just wrong and they took this functionality out:
```
 * The HTTP Bearer authentication strategy authenticates requests based on
 * a bearer token contained in the `Authorization` header field, `access_token`
 * body parameter, or `access_token` query parameter.
```

I've tried both access_token in the query string and the post body and it doesn't work.

**Comment by codecowboy** [comment]
For anyone else having this issue, I also posted here - https://github.com/jaredhanson/passport-http-bearer/issues/42

**Comment by julianlam** [comment]
@codecowboy Are you still experiencing issues getting the token parsed?

**Comment by codecowboy** [comment]
@julianlam you can probably close this. I wrote a script which sets the appropriate headers for me.
