### ISSUE TITLE
Plugin Does not appear in NodeBB 0.9 admin panel

### ISSUE THREAD

**Issue by codecowboy** [NodeBB/nodebb-plugin-write-api#45]
I installed via ```https://github.com/NodeBB/nodebb-plugin-write-api.git``` and activated the plugin. It does not appear in the Plugin menu after restarting NodeBB

I found I had to run ``npm install``` in the ```nodebb-plugin-write-api/``` folder to install the missing passport-http-bearer dependency

**Comment by julianlam** [comment]
v3.2.2 should show up in the list shortly. Thanks!

**Comment by julianlam** [comment]
Closed via https://github.com/NodeBB/nodebb-plugin-write-api/commit/c18a93b7186bf15a4fd0cdecfe721c935ed9c7f3
