### ISSUE TITLE
Trying to remove a user from a group which they don't belong still decrements membercount

### ISSUE THREAD

**Issue by quarkboy** [NodeBB/nodebb-plugin-write-api#55]
The groups/:slug/membership DESTROY route doesn't check whether the uid is a member of the group before calling Groups.leave.

The logic of Groups.leave assumes that the uid is a member, and it decrements membercount and then destroys the group if it goes to zero!  

I think you need to add in a isMember check before calling Groups.leave in this route.

(For now I'll get around it by using the READ api and doing the isMember check myself, but I think the behavior of groups/:slug/membership DESTROY when the uid isn't a member of the group should be to do nothing and/or return an error like 402)

**Comment by julianlam** [comment]
You're completely right! Let's get this fixed...

**Comment by julianlam** [comment]
v4.2.3
