### ISSUE TITLE
User DELETE route fails withTypeError: callback is not a function

### ISSUE THREAD

**Issue by quarkboy** [NodeBB/nodebb-plugin-write-api#60]
I'm pretty sure this is a typo in line 51:

`async.apply(Users.delete, req.params.uid)`

should be

`async.apply(Users.delete, req.user.uid, req.params.uid)`

**Comment by julianlam** [comment]
Already fixed, please use latest version.

Julian Lam

Co-Founder, NodeBB Inc.
619-341 King Street East
Toronto, Ontario
M5A 1L1

**Comment by julianlam** [comment]
https://github.com/NodeBB/nodebb-plugin-write-api/commit/a1ad954699f65111dea788a1965e34f3e905d993

**Comment by quarkboy** [comment]
I searched for an issue but didn't find one... guess I should have searched the commits, too!

3 days ago, huh?  fine then :).

**Comment by julianlam** [comment]
;)
