### ISSUE TITLE
Postman help

### ISSUE THREAD

**Issue by crobinson42** [NodeBB/nodebb-plugin-write-api#61]
I just ran into this plugin and excited to use it but it's giving me a headache, lol. Is there some kind of trick to using postman?

https://www.dropbox.com/s/oqg02f62dp030v5/Screenshot%202016-08-02%2018.32.09.png?dl=0

It continues to say there's an issue with the params `username` but i'm clearly putting username in the params being passed, I've also tried several different variations and same thing.

**Comment by julianlam** [comment]
Looks like you're passing the data as a query string, when they should be passed in the POST body (see the section below in your screenshot for key value style input)

**Comment by crobinson42** [comment]
https://www.dropbox.com/s/0k3glqb0jvbjsia/Screenshot%202016-08-02%2019.01.15.png?dl=0

I get the same response, unfortunately.

**Comment by julianlam** [comment]
Try not sending it as form data  ...

**Comment by crobinson42** [comment]
Nothing. Do you use Postman?

**Comment by crobinson42** [comment]
ahhh! I'm about dumb as a rock. lol, apparently that error it's returning means the username is already taken. **Open an issue to have a better description?** LOL

**Comment by julianlam** [comment]
Quite odd, the error shouldn't be showing that if a username is taken. In any case, I test using cURL.
