### ISSUE TITLE
write-api.tpl dosen't show up automatically

### ISSUE THREAD

**Issue by riddle911** [NodeBB/nodebb-plugin-write-api#62]
After `git and npm i` and restart nodebb
 I cannot open the page `plugin`-`write-api`.
I found it dosen't generate a write-api.tpl file into /nodebb/public/templates/admin/plugins.
I put a copy in it. Then it works.
It's so weird.  : )

**Comment by julianlam** [comment]
You need to run ./nodebb build after installation and activation
