### ISSUE TITLE
Require https is broken

### ISSUE THREAD

**Issue by RoiEXLab** [NodeBB/nodebb-plugin-write-api#66]
On my server I'm using nginx to reverse proxy my nodebb installation.
I edited the config.json file to use an https adress, but when I enter `curl -H "Authorization: Bearer <token>"  https://<myserver>/api/v1/users/<uid>/tokens` I just get `{"code":"upgrade-required","message":"HTTPS is required for requests to the write api, please re-send your request via HTTPS","params":{}}`
As expected this doesn't occurs when the checkbox is unchecked.
This isn't a big problem, since the only way to connect to my server is using https anyway (http is redirected).
I just wanted to mention this...

**Comment by RoiEXLab** [comment]
@julianlam Haven't checked if this is working lately.
As you can tell I opened this issue one year ago, so this might either already be fixed or the config changed which might have fixed this as well.
Feel free to close this issue. 
Maybe I'll report back in the future, but since my server enforces HTTPS anyways there's not much value in such a feature for me anyways

**Comment by julianlam** [comment]
:smile: Yeah, I imagine maybe it was fixed since the issue was opened. Cheers.
