### ISSUE TITLE
 registration and autologon about nodebb-plugin-write-api

### ISSUE THREAD

**Issue by cdscawd** [NodeBB/nodebb-plugin-write-api#75]
Hello:My forum is through a App URL jump in, I want to complete the automatic registration and autologon function, please ask me how to realize? Do you have any ideas? How to coding `nodebb-plugin-write-api` in my nodebb website?

**Comment by julianlam** [comment]
https://community.nodebb.org/topic/11146/registration-and-autologon-about-nodebb-plugin-write-api
