### ISSUE TITLE
Delete user by email OR retrieve user by email

### ISSUE THREAD

**Issue by d0dge** [NodeBB/nodebb-plugin-write-api#84]
The API is fantastic and allows me to (nearly) automate membership in conjunction with my own website.

The only problem I'm having so far is that I'd like to be able to delete users when they cancel their subscription to my site.  There is obviously a delete user method but it requires a uid, something that's largely internal to the forum and my website never finds out what the uid is for any created user.

Can there be a way of either passing an email address to the delete method instead of a uid, or a way of retrieving a user by their email address so I can find out the uid prior to calling the delete method?

**Comment by barisusakli** [comment]
Can't you use `User.getUidByEmail` from the core User module?

**Comment by julianlam** [comment]
I think @d0dge is interfacing with NodeBB only via the write API, so in this case a delete user via email option may be useful.

**Comment by julianlam** [comment]
As the route itself is `/users/<uid>`, it is not feasible to overload the method with uid resolution via email (as the uid is required as a parameter). It'll be easier to expose a uid search tool for you via a new route.

**Comment by d0dge** [comment]
Yes I thought that might be the case.  Retrieving the uid first via a separate call and then passing that to the delete route will work fine :)

**Comment by julianlam** [comment]
@d0dge So I wrote the user search API for write-api, then realized we already have this in NodeBB 😫 

The route is `/api/users?term=<term>`

**Comment by julianlam** [comment]
... don't believe search by email is allowed via that route. Was that required, or is username enough?

**Comment by d0dge** [comment]
I guess speaking selfishly, email would be better as our users can change their handles but not their signup email addresses (not without request anyway).  I could just stop them from being able to change their usernames as well though :)

**Comment by d0dge** [comment]
Just realised this can be done like so:

/api/user/email/<emailaddress>
