### ISSUE TITLE
POST /posts/:pid/vote missing delta

### ISSUE THREAD

**Issue by Kryjite** [NodeBB/nodebb-plugin-write-api#85]
What am I doing wrong? v2 gives the same result
![screenshot](https://user-images.githubusercontent.com/26029326/33227831-91dc68f4-d1ce-11e7-8ff3-53251dfa9a7b.png)

**Comment by julianlam** [comment]
You'll need to send your _uid and delta parameters in the POST body payload, and not as a query string 🙂

Also make sure you have bearer authentication so your cells are properly authenticated
