### ISSUE TITLE
PUT /api/v2/users/:uid ignores :uid

### ISSUE THREAD

**Issue by danieleisenhardt** [NodeBB/nodebb-plugin-write-api#89]
When sending a put request to this endpoint the uid in the uri was ignored by the api. It created a database record with `"_key" : "user:undefined"` instead of updating the intended user.

This problem can be circumvented by adding the uid to the request body as well, but it took me a while to figure that out.

**Comment by julianlam** [comment]
Oh, that seems like a bug... if `req.params.uid` is present, it should use that uid, it shouldn't use the uid passed in `_uid`...

If it does, it sounds like it's completely ignoring `req.params.uid` and dropping to the fallback behaviour which is "update the calling user", which is read from `_uid`.

**Comment by julianlam** [comment]
v5.1.1
