### ISSUE TITLE
API Questions

### ISSUE THREAD

**Issue by t0rched** [NodeBB/nodebb-plugin-write-api#92]
More of a few questions than anything.

1) What's the best way to return a list of topics, from a category. This API, or some sort of feed plugin? I don't see the ability currently in the documentation. I could do this with my application via MongoDB, so it might not be valueable.

2) I can't seem to get the multi-part/file upload working. Here is my bit of relevant Minecraft Spigot plugin code in Java using OKHTTP:

OkHttpClient client = new OkHttpClient();

MediaType mediaType = MediaType.parse("multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW");
RequestBody body = RequestBody.create(mediaType, "------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"files\"; filename=\""+new File(getDataFolder()+"/motd.txt")+"\"\r\nContent-Type: image/gif\r\n\r\n\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW--");
Request request = new Request.Builder()
  .url("https://myurl/api/v1/util/upload/?_uid=1")
  .post(body)
  .addHeader("content-type", "multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW")
  .addHeader("Content-Type", "application/x-www-form-urlencoded")
  .addHeader("Authorization", "Bearer MYTOKEN")
  .addHeader("Cache-Control", "no-cache")
  .build();

Response response = client.newCall(request).execute();    			
sender.sendMessage(chat_prefix + ChatColor.GREEN + "Smile!");
System.out.println("[NodeDirt] Response: " + response);
} catch (IOException e) {
	System.out.println("Error: " + e);
}

The new File(getDataFolder()+"/motd.txt" file object is simply something I know exists in code that precursors this call. 

I have been using Postman to debug the HTTP calls, and this is literally the code it tells me to use upon making a successful file upload via it. 

However, I notice 2 issues with this code. 

A) There was only one file object in the code it provided. 

B) Postman, seems to fail when only using 1 file. Yet attaching 2 worked, and returned the proper result for the 2 files and their new assets location. 

This seemed odd. Since the code from that same saved Postman, would only reference 1 of the files, so I end up with the above. 

When executing the bit of code via the application, it returns error 500. Not "invalid files" which I would normally get when only attaching 1 file via Postman application. 

Any advice?

**Comment by julianlam** [comment]
If you're getting a 500, chances are there's an error stack trace in the server itself. You may want to see if one was outputted, may give you a better idea behind what happened on the NodeBB side.

As for retrieving topics, `GET /api/category/:cid`... that's the read-only API that comes with all NodeBB installs.

**Comment by KipperedSnack** [comment]
Thank you so much!
