### ISSUE TITLE
error: /assets/templates/admin/plugins/write-api.js

### ISSUE THREAD

**Issue by co-owner** [NodeBB/nodebb-plugin-write-api#93]
https://i.imgur.com/BlQzFh4.png

Error: ENOENT: no such file or directory, open 'C:\Users\User\Downloads\1.7.x\NodeBB\build\public\templates\admin\plugins\write-api.tpl'

**Comment by julianlam** [comment]
1. Are you using the write api?
1. If so, did `./nodebb build` complete without issues?
1. If not, `./nodebb reset -p write-api`

**Comment by co-owner** [comment]
./nodebb build
thanks to julianlam,it works now.
